import { Fragment } from "react";
import styles from "./MentionBadge.module.css";

/** Numeric unread/mention count — used on room list items and the rail bell. */
export function CountBadge({ count, outline = false }: { count: number; outline?: boolean }) {
  if (count <= 0) return null;
  return (
    <span className={[styles.count, outline ? styles.countOutline : ""].join(" ")}>
      {count > 99 ? "99+" : count}
    </span>
  );
}

/** "AI" tag rendered next to messages from the FishoAI bot user. */
export function AiTag() {
  return (
    <span className={styles.aiTag} title="Generated by FishoAI">
      AI
    </span>
  );
}

// Matches either an @mention (including the @channel / @here broadcast
// tokens — styled the same as a regular mention, no special-casing needed
// visually) or a bare http(s) URL. Kept as one alternation + one split so
// mentions and links interleave correctly regardless of order in the text.
const MENTION_OR_LINK = /(@\w+|https?:\/\/\S+)/g;

/** Renders message body text with @mentions (incl. @channel/@here) styled
 * distinctly (bold + underline, no color) and bare URLs rendered as real,
 * clickable links — no server-side fetching/unfurling, just text -> <a>. */
export function MentionText({ text }: { text: string | null | undefined }) {
  // Attachment-only messages (no typed text) can have a null/empty body —
  // render nothing rather than crashing on .split(null).
  const parts = (text ?? "").split(MENTION_OR_LINK);
  return (
    <>
      {parts.map((part, i) => {
        if (part.startsWith("@")) {
          return (
            <span key={i} className={styles.mention}>
              {part}
            </span>
          );
        }
        if (/^https?:\/\//.test(part)) {
          return (
            <a key={i} href={part} target="_blank" rel="noopener noreferrer" className={styles.link}>
              {part}
            </a>
          );
        }
        return <Fragment key={i}>{part}</Fragment>;
      })}
    </>
  );
}

/** Small curated emoji grid for the reaction picker — intentionally not a
 * heavy emoji-mart-style dependency, just enough common reactions. */
export const REACTION_EMOJI = [
  "👍", "❤️", "😂", "🎉", "😮", "😢", "🔥", "👀",
  "✅", "❌", "🙏", "👏", "🚀", "😅", "🤔", "💯",
];
