"""
Django settings for fishofisho project.

Generated by 'django-admin startproject' using Django 5.2.1.
For more information: https://docs.djangoproject.com/en/5.2/topics/settings/
"""

import os
from pathlib import Path
import sys
import dj_database_url
from dotenv import load_dotenv

# ============================================
# 1. LOAD ENVIRONMENT VARIABLES
# ============================================
# Load .env file from project root
env_path = Path(__file__).resolve().parent.parent / '.env'
load_dotenv(env_path)

# Debug info
print("=" * 50)
print("🔧 Loading Django Settings...")
print(f"📁 .env path: {env_path}")
print(f"✅ .env exists: {env_path.exists()}")

# ============================================
# 2. PATH CONFIGURATION
# ============================================
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================
# 3. SECURITY SETTINGS
# ============================================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-fallback-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS for Railway deployment
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.railway.app']
# Add Railway static URL if present
if 'RAILWAY_STATIC_URL' in os.environ:
    ALLOWED_HOSTS.append(os.environ['RAILWAY_STATIC_URL'])

# Add from environment variable
allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if allowed_hosts_env:
    ALLOWED_HOSTS.extend([host.strip() for host in allowed_hosts_env.split(',') if host.strip()])

# Debug output
print(f"🔐 DEBUG: {DEBUG}")
print(f"🌐 ALLOWED_HOSTS: {ALLOWED_HOSTS}")
print(f"🔑 SECRET_KEY loaded: {'YES' if SECRET_KEY else 'NO'}")

# ============================================
# 4. APPLICATION DEFINITION
# ============================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'playground',  # Your custom app
]

# Add debug_toolbar only in development
if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')
    print("🔧 Debug toolbar ENABLED")

INTERNAL_IPS = ["127.0.0.1"]

# ============================================
# 5. MIDDLEWARE
# ============================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # REQUIRED for static files on Railway
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add debug toolbar middleware only in development
if DEBUG:
    MIDDLEWARE.insert(3, 'debug_toolbar.middleware.DebugToolbarMiddleware')

# ============================================
# 6. TEMPLATES
# ============================================
ROOT_URLCONF = 'fishofisho.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fishofisho.wsgi.application'

# ============================================
# 7. DATABASE
# ============================================
# Database configuration for both SQLite (local) and PostgreSQL (Railway)
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

print(f"🗄️ Database: {DATABASES['default']['ENGINE']}")

# ============================================
# 8. PASSWORD VALIDATION
# ============================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================
# 9. INTERNATIONALIZATION
# ============================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ============================================
# 10. STATIC FILES (CRITICAL FOR RAILWAY)
# ============================================
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # REQUIRED for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # REQUIRED

# For development static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

print(f"📁 STATIC_ROOT: {STATIC_ROOT}")

# ============================================
# 11. DEFAULT PRIMARY KEY FIELD
# ============================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# 12. TESTING FLAG
# ============================================
TESTING = "test" in sys.argv or "PYTEST_VERSION" in os.environ

# ============================================
# 13. AUTHENTICATION
# ============================================
LOGIN_URL = 'login'  # Matches your URL name
LOGIN_REDIRECT_URL = 'home'  # Where to redirect after login

# ============================================
# 14. MEDIA FILES (UPLOADS)
# ============================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

<<<<<<< HEAD
# ============================================
# 15. AI API KEYS (GEMINI / OPENAI)
# ============================================
# Try to get API key from multiple sources
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY') or os.environ.get('OPENAI_API_KEY', '')
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Debug output for API keys
print(f"🤖 GEMINI_API_KEY loaded: {'YES' if GEMINI_API_KEY else 'NO'}")
if GEMINI_API_KEY:
    print(f"🔑 Gemini key starts with: {GEMINI_API_KEY[:15]}...")
    print(f"📏 Gemini key length: {len(GEMINI_API_KEY)} characters")

print(f"🤖 OPENAI_API_KEY loaded: {'YES' if OPENAI_API_KEY else 'NO'}")

# ============================================
# 16. SECURITY SETTINGS FOR PRODUCTION
# ============================================
if not DEBUG:
    print("🔒 PRODUCTION security settings ENABLED")
    
    # Security settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # CSRF trusted origins for Railway
    CSRF_TRUSTED_ORIGINS = ['https://*.railway.app']
    
    # HSTS Settings (only if you have SSL)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    print("🔓 DEVELOPMENT mode - security relaxed")

# ============================================
# 17. RAILWAY-SPECIFIC SETTINGS
# ============================================
if 'RAILWAY' in os.environ:
    print("🚂 Railway environment detected")
    # Ensure static files work on Railway
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_MANIFEST_STRICT = False
    WHITENOISE_ALLOW_ALL_ORIGINS = True
    
    # Add Railway domain to CSRF origins
    if 'RAILWAY_STATIC_URL' in os.environ:
        railway_domain = os.environ['RAILWAY_STATIC_URL']
        CSRF_TRUSTED_ORIGINS.append(f"https://{railway_domain}")

# ============================================
# 18. EMAIL SETTINGS (OPTIONAL)
# ============================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = os.environ.get('EMAIL_PORT', 587)
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

print("=" * 50)
print("✅ Settings loaded successfully!")
print("=" * 50)
=======
>>>>>>> ac185296a50deb7deab25e98a3a7d2020dabd32a
