# Generated by Django 5.2.1 on 2026-08-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_chatbot_privateconversation_privatemessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatbot',
        ),
    ]
