# Generated by Django 5.2.1 on 2026-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_backfill_role_and_room_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
