# Generated by Django 5.2.1 on 2026-08-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_message_deleted_at_message_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
