# Generated by Django 5.2.1 on 2026-08-11 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_message_client_id_privatemessage_client_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('message', 'Message'), ('follow', 'Follow'), ('like', 'Like'), ('thread_reply', 'Thread Reply')], max_length=20),
        ),
        migrations.CreateModel(
            name='ThreadFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_follows', to='playground.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('root_message', 'user')},
            },
        ),
    ]
