# Generated by Django 5.2.1 on 2026-08-11 18:03
# Drops PrivateMessage.receiver/is_read now that 0017 has backfilled their
# information into ConversationRead. See that migration's docstring for
# backfill limitations.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0017_backfill_conversationread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='receiver',
        ),
    ]
