# Generated by Django 5.2.1 on 2026-08-11 19:06

import django.core.files.storage
import playground.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0019_notificationpreference_roomnotificationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\LENOVO\\Desktop\\Django\\activite\\protected_media\\attachments'), upload_to=playground.models._attachment_upload_to),
        ),
    ]
